# -*- coding: utf-8 -*-
"""Formula Data Absen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EncpYgKMUD4vY0EdcMg4P8lB1pe006WH

# INSTALASI
- Baris ini cuma perlu di run sekali saja untuk instalasi
"""

!pip install pdfplumber pandas requests

"""# DOWNLOAD TEMPLATE EXCEL
- Run baris ini untuk mendownload template excel untuk input data
"""

import pandas as pd
from google.colab import files

# contoh buat templatenya
data_template = {
    'Nama_Pegawai': ['ACHMAD SHOLIKIN', 'CONTOH PEGAWAI 2'],
    'ID_Pegawai': ['7f66455c-ee57-11ea-8acf-000c29766abb', '35951734-ece8-11ea-9cd7-000c29766abb'],
    'Tanggal_Akhir': [31, 31],
    'Bulan': ['03', '03'],
    'Tahun': [2026, 2026]
}

df_template = pd.DataFrame(data_template)
template_name = 'template_download_absensi.xlsx'
df_template.to_excel(template_name, index=False)

print("--- Template Excel Berhasil Dibuat ---")
files.download(template_name)

"""# DOWNLOAD PDF
- Baris ini untuk download all data PDF pegawai
"""

import requests
import pandas as pd
import io
from google.colab import files

def download_pdf_dari_excel():
    print("Upload file Excel yang sudah diisi:")
    uploaded = files.upload()

    if not uploaded:
        print("Upload dibatalkan.")
        return

    file_name = list(uploaded.keys())[0]

    try:
        df = pd.read_excel(io.BytesIO(uploaded[file_name]))

        df['Bulan'] = df['Bulan'].astype(str).str.zfill(2)
        df['Tanggal_Akhir'] = df['Tanggal_Akhir'].astype(str).str.zfill(2)
    except Exception as e:
        print(f"Gagal membaca file Excel: {e}")
        return

    base_url = "https://teko-cak.surabaya.go.id/cetak_new/lap_per_pegawai2/"
    instansi = "3.10.00.00.00"

    print(f"\n--- Memulai Proses Download ({len(df)} baris data) ---")

    # looping row excel
    for index, row in df.iterrows():
        nama = row['Nama_Pegawai']
        id_pegawai = row['ID_Pegawai']
        tgl = row['Tanggal_Akhir']
        bln = row['Bulan']
        thn = row['Tahun']

        params = {
            'tgl': tgl,
            'bulan': bln,
            'tahun': thn,
            'id_instansi': instansi,
            'id_pegawai': id_pegawai,
            'type': 'pdf'
        }

        pdf_file_name = f"Laporan_{nama}_{tgl}-{bln}-{thn}.pdf"

        try:
            print(f"Sedang mendownload laporan: {nama}...")
            response = requests.get(base_url, params=params, stream=True, timeout=30)

            if response.status_code == 200:
                with open(pdf_file_name, 'wb') as f:
                    f.write(response.content)

                files.download(pdf_file_name)
            else:
                print(f"--- Gagal proses data {nama}. Status: {response.status_code} ---")

        except Exception as e:
            print(f"--- Error pada {nama}: {str(e)} ---")

    print("\n--- Semua Proses Selesai ---")

download_pdf_dari_excel()

"""# DOWNLOAD DATA EXCEL

- Baris ini untuk download all data Excel pegawai
"""

import requests
import pandas as pd
import io
import os
from google.colab import files

def download_excel_fix():
    print("Upload file Excel:")
    uploaded = files.upload()

    if not uploaded:
        print("Upload dibatalkan.")
        return

    input_file_name = list(uploaded.keys())[0]

    try:
        df = pd.read_excel(io.BytesIO(uploaded[input_file_name]))

        df['Bulan'] = df['Bulan'].astype(str).str.zfill(2)
        df['Tanggal_Akhir'] = df['Tanggal_Akhir'].astype(str).str.zfill(2)
    except Exception as e:
        print(f"Gagal membaca file template: {e}")
        return

    base_url = "https://teko-cak.surabaya.go.id/cetak_new/lap_per_pegawai2/"
    instansi = "3.10.00.00.00"

    print(f"\n--- Memulai Download Versi Excel (.xlsx) ({len(df)} data) ---")

    # 3. Looping Download
    for index, row in df.iterrows():
        nama = row['Nama_Pegawai']
        id_pegawai = row['ID_Pegawai']
        tgl = row['Tanggal_Akhir']
        bln = row['Bulan']
        thn = row['Tahun']

        params = {
            'tgl': tgl,
            'bulan': bln,
            'tahun': thn,
            'id_instansi': instansi,
            'id_pegawai': id_pegawai,
            'type': 'xls'
        }

        output_xlsx_name = f"Data_Absensi_{nama}_{tgl}-{bln}-{thn}.xls"

        try:
            print(f"Mengunduh XLSX: {nama}...")
            response = requests.get(base_url, params=params, stream=True, timeout=30)

            if response.status_code == 200:
                with open(output_xlsx_name, 'wb') as f:
                    f.write(response.content)

                files.download(output_xlsx_name)
            else:
                print(f"❌ Gagal download XLSX untuk {nama}. Status: {response.status_code}")

        except Exception as e:
            print(f"⚠️ Error pada {nama}: {str(e)}")

    print("\n--- Proses Download Excel Selesai ---")

download_excel_fix()

import requests
import pandas as pd
import io
from google.colab import files

def download_pdf_dari_excel():
    print("Upload file Excel yang sudah diisi:")
    uploaded = files.upload()

    if not uploaded:
        print("Upload dibatalkan.")
        return

    file_name = list(uploaded.keys())[0]

    try:
        df = pd.read_excel(io.BytesIO(uploaded[file_name]))

        df['Bulan'] = df['Bulan'].astype(str).str.zfill(2)
        df['Tanggal_Akhir'] = df['Tanggal_Akhir'].astype(str).str.zfill(2)
    except Exception as e:
        print(f"Gagal membaca file Excel: {e}")
        return

    base_url = "https://teko-cak.surabaya.go.id/cetak_new/lap_per_pegawai2/"
    instansi = "3.10.00.00.00"

    print(f"\n--- Memulai Proses Download ({len(df)} baris data) ---")

    # looping row excel
    for index, row in df.iterrows():
        nama = row['Nama_Pegawai']
        id_pegawai = row['ID_Pegawai']
        tgl = row['Tanggal_Akhir']
        bln = row['Bulan']
        thn = row['Tahun']

        params = {
            'tgl': tgl,
            'bulan': bln,
            'tahun': thn,
            'id_instansi': instansi,
            'id_pegawai': id_pegawai,
            'type': 'pdf'
        }